MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence:true
end

MusicApp/app/models/user.rb
class User < ApplicationRecord
    validates :email, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: {minimum: 6}, allow_nil: true

    attr_reader :password

    after_initialize :ensure_session_token

    # finding the user instance based on input parameters
    def self.find_by_credentials(user_email, user_password)
        user = User.find_by(email: user_email)

        return nil unless user && user.is_password?(user_password)
        user
    end

    # creating a BCrypt::Password instance and assigning it to user.password_digest
    def password=(password)
        @password = password
        # BCrypt::Password.create hashes a secret, returning a BCrypt::Password instance aka ******
        self.password_digest = BCrypt::Password.create(password)
    end

    # encrypting password to password_digest
    def is_password?(password)
        bcrypt_pass = BCrypt::Password.new(self.password_digest)
        # different from User#is_password?, BCryptObject#is_password?
        bcrypt_pass.is_password?(password)
    end

    # reassigning session token for the purpose of the user logging in and logging out
    def reset_session_token!
        self.update(session_token: self.class.generate_session_token)
        # or
        # self.session_token = SecureRandom.urlsafe_base64

        self.save!
        self.session_token
    end

    private
    # generates a random base64 session token 
    def self.generate_session_token
        SecureRandom.urlsafe_base64
    end

    # check if the user has a session token, if not assign one
    def ensure_session_token
        self.session_token ||= self.class.generate_session_token
    end
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :current_user_id, :logged_in?
    
    def current_user
        # only run if session[:session_token] exists
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def current_user_id
        current_user ? current_user.id : nil
    end
    
    def logged_in?
        # returns boolean for truth-y and false-y user instance
        !!current_user
    end

    # logging in the user
    def log_in_user!(user)
        session[:session_token] = user.reset_session_token!
    end

    # def ensure_logged_in
    #     redirect_to new_session_url if current_user.nil?
    # end
end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index
        @bands = Band.all
        render :index
    end

    def show
        @band = Band.find_by(id: params[:id])
        render :show
    end

    def new
        @band = Band.new
        render :new
    end

    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def edit
        @band = Band.find_by(id: params[:id])
        render :edit
    end
    
    def update
        @band = Band.find_by(id: params[:id])
        if @band.update(band_params)
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end

    def destroy
        # review if we NEED to use .find_by
        @band = Band.find_by(id: params[:id])
        @band.destroy
        redirect_to bands_url
    end

    private
    def band_params
        params.require(:band).permit(:name)
    end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :new
    end

    # logging in means session[:session_token] == user.session_token
    def create
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        
        if user
            session[:session_token] = user.reset_session_token!
            redirect_to user_url(user)
        else
            flash.now[:errors] = user.errors.full_messages
            render :new
        end
    end

    # logging out means session[:session_token] != user.session_token
    def destroy
        @current_user.reset_session_token!
        session[:session_token] = nil
        render :new
    end
end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        # user template to store user inputs into user_params
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            # session[:session_token] = @user.reset_session_token!
            # return to this section
            # redirect_to to_what...
        else
            flash.now[:errors] = @user.errors.full_message
            render :new
        end
    end

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/views/bands/edit.html.erb
<p>BAND EDIT</p>

MusicApp/app/views/bands/index.html.erb
<h1>BANDS</h1>

<ul>
    <% @bands.each do |band| %>
        <li><button><a href="<%= band_url(band) %>"><%= band.name %></a></button></li>
    <% end %>
</ul>

<br>

<h2>LINKS</h2>
<button><a href="<%= new_band_url %>">Register New Band</a></button>

MusicApp/app/views/bands/new.html.erb
<h1>Add A Band</h1>

<form action="<%= bands_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="band-name">Band Name:</label>
    <input id="band-name" type="text" name="band[name]" value="<%= @band.name %>">

    <input type="submit">
</form>

MusicApp/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if logged_in? %>
        <form action="<%= session_url %>" method="POST">
          <input type="hidden" name="_method" value="DELETE">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <button>Log Out</button>
        </form>
      <% else %>
        <button><a href="<%= new_session_url %>">Log In</a></button>
        <br>
        <button><a href="<%= new_user_url %>">Sign Up</a></button>
      <% end %>
    </nav>

    <%= yield %>
  </body>
</html>

MusicApp/app/views/users/new.html.erb
<p> This is Signup Page </p>

MusicApp/app/views/users/show.html.erb
<p> This is Show User Profile Page </p>